---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hpi-linux
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
- type: files
  files:
  - source: system
    destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
- type: dnf
  repos:
    copr:
    - dejan/lazygit
    - pgdev/ghostty
    - tofik/nwg-shell
    - wezfurlong/wezterm-nightly

- type: rpm-ostree
  repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

  install:
  - pipewire
  - wireplumber
  - pipewire-pulseaudio
  - pipewire-alsa
  - nwg-displays
  - fd-find
  - mumble
  - ShellCheck
  - alsa-lib-devel
  - pkgconfig
  - qemu-kvm
  - libvirt
  - virt-manager
  - virt-install
  - gnome-boxes
  - virt-viewer
  - atuin
  - btop
  - cargo
  - chromium
  - clangd
  - code
  - evince
  - gnome-music
  - gcc
  - gedit
  - gh
  - ghostty
  - gnome-extensions-app
  - gnome-tweaks
  - golang
  - helix
  - lazygit
  - libreoffice
  - libreoffice-langpack-de
  - libreoffice-langpack-en
  - make
  - micro
  - mpv
  - nodejs
  - papers
  - rustup
  - starship
  - tealdeer
  - uv
  - zoxide
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - xwaylandvideobridge
  - wezterm
  # remove:
  # example: removing firefox (in favor of the flatpak)
  # "firefox" is the main package, "firefox-langpacks" is a dependency
  # - firefox
  # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

- type: default-flatpaks
  configurations:
  - notify: true
    scope: system
    install:
    - org.mozilla.firefox
    - org.mozilla.Thunderbird
    - org.gnome.Loupe
    - org.telegram.desktop
    - com.rtosta.zapzap
    - md.obsidian.Obsidian
    - it.mijorus.gearlever
    - com.raggesilver.BlackBox

- type: brew

- type: chezmoi
  repository: "https://github.com/rocketrene/dotfiles" # my dotfiles repo
  all-users: true # make users have to enable chezmoi manually
  file-conflict-policy: replace # override changed files with those from the repo

- type: gnome-extensions
  install:
  - Night Theme Switcher
  - Blur my Shell # Notice how extension is named "Blur my Shell" & not "Blur My Shell"?
  # uninstall:

- type: signing # this sets up the proper policy & signing files for signed images to work fully

- type: script
  scripts:
  - install-zoom.sh
